web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.refinedev.io'
  container_name: gitlab
  environment:
    GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
    - '5005:5005'
  volumes:
    - '/refine/service/gitlab/config:/etc/gitlab'
    - '/refine/service/gitlab/logs:/var/log/gitlab'
    - '/refine/service/gitlab/data:/var/opt/gitlab'
    - '/refine/service/gitlab/backups:/var/opt/gitlab/backups'
