version: '3'
# See https://docs.docker.com/compose/overview/ for more information.

# If you make changes to this file or any related files, apply them by
# navigating to the directory that holds this file and run this as root:
#   docker-compose down; docker-compose up -d

# Create a network for our containers.
networks:
  frontend:

# Create persistent Docker volumes to preserve important data.
# We don't want our data to be lost when restarting containers.
#volumes:
  # For storing GitLab's configuration files:
#  vol-gitlab-config:
  # For storing GitLab's logs:
#  vol-gitlab-logs:
  # For storing GitLab's application data:
#  vol-gitlab-data:

# Create our containers.
services:
  # The main front-end application.
  gitlab:
    # To stick to a specific version, replace "latest" with a tag from:
    # https://hub.docker.com/r/gitlab/gitlab-ce/tags/
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: "gitlab.refinedev.io"
    container_name: gitlab
    ports:
      - "22:22"    # Change to "2222:22" if the host needs port 22.
      - "80:80"
      - "443:443"
      - "5005:5005"
    networks:
      - frontend
    volumes:
      # Ensure GitLab content persist between restarts.
      - '/refine/service/gitlab/config:/etc/gitlab'
      - '/refine/service/gitlab/logs:/var/log/gitlab'
      - '/refine/service/gitlab/data:/var/opt/gitlab'
      - '/refine/service/gitlab/backups:/var/opt/gitlab/backups'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add gitlab.rb configuration here, each on its own line.
        # See: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
        external_url 'http://gitlab.refinedev.io'
        registry_external_url 'http://gitlab.refinedev.io:5005'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'mail.refine.co.kr'
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_user_name'] = 'gitlab@refine.co.kr'
        gitlab_rails['smtp_password'] = 'Refine$710'
        gitlab_rails['smtp_domain'] = 'refine.co.kr'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['gitlab_email_from'] = 'gitlab@refine.co.kr'
        gitlab_rails['gitlab_email_reply_to'] = 'gitlab@refine.co.kr'
